[server]
port = 8080
data_dir = "/app/data"
hostname = "https://podsync.marcin-lis.pl"

#[storage]
#type = "s3"

#[storage.local]
#data_dir = "/app/data" # Don't change if you run podsync via docker

#[storage.s3]
#endpoint_url = "s3.us-east-005.backblazeb2.com"
#region = "us-east-005"
#bucket = "ml-podsync"

[tokens]
youtube = "AIzaSyAFQiBw3zeCW0hQZ46tSNARytpKZQviXds"

[feeds]
  [feeds.naukatolubie]
  url = "https://www.youtube.com/channel/UCtcUMxUSMWUNBfOaKUv5cjg"
  page_size = 5
  update_period = "12h"
  quality = "high"
  format = "audio"
  clean = { keep_last = 10 }
  opml = true
  private_feed = true
  # Optional feed customizations
  [feeds.naukatolubie.custom]
#  title = "Level1News"
#  description = "News sections of Level1Techs, in a podcast feed!"
#  author = "Level1Tech"
#  cover_art = "{IMAGE_URL}"
#  cover_art_quality = "high"
  category = "Science"
#  subcategories = ["Documentary", "Tech News"]
#  explicit = true
  lang = "pl"
#  author = "Mrs. Smith (mrs@smith.org)"
#  ownerName = "Mrs. Smith"
#  ownerEmail = "mrs@smith.org"

  [feeds.swiatodzera]
  url = "https://www.youtube.com/playlist?list=PLvLrA9jH7wQiRGF2CHEqgkd23KaBZM6em"
  page_size = 5
  update_period = "12h"
  quality = "high"
  format = "audio"
  clean = { keep_last = 10 }
  opml = true
  private_feed = true
  [feeds.swiatodzera.custom]
  lang = "pl"


[database]
  badger = { truncate = true, file_io = true } # See https://github.com/dgraph-io/badger#memory-usage

[downloader]
self_update = true # Optional, auto update youtube-dl every 24 hours
timeout = 15
