services:
  podsync:
    image: mxpv/podsync:v2.5
    container_name: podsync
    ports:
      - 80:80
    volumes:
      - ./data:/data/
      - ./data:/app/data/
      - ./config.toml:/app/config.toml
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    name: npm_network
