services:
  podsync:
    image: mxpv/podsync:v2.5
    container_name: podsync
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data:/data/
      - ./data:/app/data/
      - ./config.toml:/app/config.toml
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    name: npm_network
